name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip install -r requirements.txt
    - name: Print IP address
      run: |
        ifconfig
    - name: Build
      run: |
        python3.9 app.py
